# Generated by Django 4.1.7 on 2023-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('interested_in', models.CharField(max_length=20)),
                ('ad_name', models.CharField(max_length=300)),
                ('email_sent', models.BooleanField(default=False)),
                ('new_lead', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=250)),
            ],
        ),
    ]
